"""certifications and audit samples

Revision ID: 017521108493
Revises: 7d2cf2254d75
Create Date: 2026-10-08 13:09:50.221928

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '017521108493'
down_revision: str | Sequence[str] | None = '7d2cf2254d75'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_version_id', sa.Uuid(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('tau', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('active', 'failed', 'superseded', 'suspended', name='certificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('cert_documents', sa.Integer(), nullable=False),
    sa.Column('n_applied', sa.Integer(), nullable=False),
    sa.Column('n_errors', sa.Integer(), nullable=False),
    sa.Column('ucb', sa.Float(), nullable=False),
    sa.Column('auto_recall', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_version_id'], ['catalog_versions.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_samples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assertion_id', sa.Uuid(), nullable=False),
    sa.Column('certification_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assertion_id'], ['assertions.id'], ),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assertion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_samples')
    op.drop_table('certifications')
    # ### end Alembic commands ###
