"""review event from_state nullable

Revision ID: 7d2cf2254d75
Revises: fc208d122d8e
Create Date: 2026-10-08 13:03:44.707231

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d2cf2254d75"
down_revision: str | Sequence[str] | None = "fc208d122d8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "review_events", "from_state", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "review_events", "from_state", existing_type=sa.VARCHAR(length=32), nullable=False
    )
    # ### end Alembic commands ###
